### ISSUE TITLE
ChickenKyiv export data

### ISSUE THREAD

**Issue by atherdon** [GroceriStar/static-data#10]
we should include this files into main file, related to ChickenKyiv project:
- [ ] Menus
- [ ] Recipes
- [ ] Ingredients
- [ ] Departments
- [ ] Users

You also should create simple tests for each exported array
- [ ] Menus
- [ ] Recipes
- [ ] Ingredients
- [ ] Departments
- [ ] Users
Please tell me what tests do you think is important for this arrays?

https://github.com/GroceriStar/static-data/blob/master/dist/data/simple/Ingredients/Ingredients.js
https://github.com/GroceriStar/static-data/blob/master/dist/data/simple/Recipe4/Recipe.js
https://github.com/GroceriStar/static-data/blob/master/dist/data/simple/Users/User.js
https://github.com/GroceriStar/static-data/blob/master/dist/data/simple/Menu/Menu.js

https://github.com/ChickenKyiv/recipe-api-only/tree/master/bin

**Comment by atherdon** [comment]
https://github.com/ChickenKyiv/recipe-api-only/commit/918bde87576125131d250868ef02ecbd1c5a4dfd

**Comment by anupmahadev** [comment]
I think we should check if all the static data type matches with the other data for example: If chicken recipe is being done, then ingredients should match with the items that are  used. This is one basic approach of test that can be made.

**Comment by atherdon** [comment]
for now, it'll be fine if we'll have tests, related to (does we have array with items - yes/no, does count of array elements match).

**Comment by atherdon** [comment]
@anupmahadev tell me if we can proceed further with this task
