### ISSUE TITLE
React Search Form import data

### ISSUE THREAD

**Issue by atherdon** [GroceriStar/static-data#14]
data from: https://github.com/ChickenKyiv/recipe-search-react/tree/master/src/data

- [x] Allergy
- [x] Courses
- [x] Cuisines
- [x] Diets
- [x] Holidays
- [x] Ingredients

You also should create simple tests for each exported array
- [x] Allergy
- [x] Courses
- [x] Cuisines
- [x] Diets
- [x] Holidays
- [x] Ingredients

Please tell me what tests do you think is important for this arrays?

https://github.com/GroceriStar/static-data/blob/master/dist/data/simple/allergies.js
https://github.com/GroceriStar/static-data/blob/master/dist/data/simple/holidays.js
https://github.com/GroceriStar/static-data/blob/master/dist/data/simple/courses.js
https://github.com/GroceriStar/static-data/blob/master/dist/data/simple/cuisines.js
https://github.com/GroceriStar/static-data/blob/master/dist/data/simple/Ingredients4/Ingredients.js
https://github.com/GroceriStar/static-data/blob/master/dist/data/simple/Diets/diets.js

**Comment by atherdon** [comment]
i add some tests, but i think we can add few tests, related to getting something from array and comparing the results

**Comment by atherdon** [comment]
@chauhannishith can you add that tests? i'm trying to push our package forward and will move soon data related to groceristar and chickenkyiv imports

**Comment by chauhannishith** [comment]
Sorry I forgot to tell you, I had pushed some tests today which according to me are enough for it. If you want any other tests then tell me those

**Comment by chauhannishith** [comment]
Is there anything else you want me to add in this package?

**Comment by atherdon** [comment]
yeah, i have a lot of plans for it.
But i want to ask - are you ok to do such things as tests? usually it's
boring for developers. if you want more hardcore stuff - tell me, ok? Btw,
main plans for this package stored in my prev repo:
https://github.com/GroceriStar/static-data


On 05-Jul-2018 at 02:48 PM, chauhannishith wrote:


Is there anything else you want me to add in this package?

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/GroceriStar/static-data/issues/14#issuecomment-402747726>,
or mute the thread

**Comment by chauhannishith** [comment]
Its not that i dont like tests but i would like to do it as secondary task

Ya i saw that you have some stuff in this repo but couldnt get what is happening exactly

**Comment by chauhannishith** [comment]
What do you want me to add in this or any other task you want me to do

**Comment by atherdon** [comment]
you can install this package at search-api-server and upgrade the import
script that we're storing at bin folder


On 06-Jul-2018 at 04:49 AM, chauhannishith wrote:


What do you want me to add in this or any other task you want me to do

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/GroceriStar/static-data/issues/14#issuecomment-402924745>,
or mute the thread

**Comment by atherdon** [comment]
sure, sorry that i didn't share it before: https://github.com/ChickenKyiv/recipe-search-api

**Comment by chauhannishith** [comment]
how does the package update on npm?
The new data which you entered I updated it and pushed it in the package

**Comment by atherdon** [comment]
@chauhannishith i published latest changes at npm
